# Generated by Django 3.1 on 2020-09-07 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usuario', '0003_auto_20200907_0147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitante',
            name='user',
        ),
        migrations.AddField(
            model_name='visitante',
            name='usuario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
